language: node_js
node_js:
  - "10"
  - "9"
  - "8"
sudo: enabled
before_install:
  - sudo ./debian_install.sh
script:
  - npm test
  - npm run lint
notifications:
  email:
    recipients:
      - qwhexz@gmail.com
    on_success: never
    on_failure: always
