language: node_js
node_js:
  - "10"
  - "9"
  - "8"
sudo: enabled
before_install:
  - sudo ./debian_install.sh
install:
  - npm install
  - npm install -g codecov istanbul
script:
  - npm test
  - npm run lint
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
notifications:
  email:
    recipients:
      - qwhexz@gmail.com
    on_success: never
    on_failure: always
